name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  smoke:
    name: Smoke check (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print environment (Unix)
        if: runner.os != 'Windows'
        run: |
          echo "Runner OS: $RUNNER_OS"
          uname -a
          pwd

      - name: List files (Unix)
        if: runner.os != 'Windows'
        run: |
          ls -la

      - name: Print environment (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Write-Output "Runner OS: $env:RUNNER_OS"
          $PSVersionTable.PSVersion
          Get-Location

      - name: List files (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Get-ChildItem -Force

      - name: Done
        run: echo "Workflow ran successfully."
