name: Hello on PR Open

on:
  pull_request:
    types: [opened]

jobs:
  say-hello:
    name: Say Hello
    runs-on: ubuntu-latest
    steps:
      - name: Hello, world
        run: |
          echo "Hello, world!"
          echo "PR #${{ github.event.pull_request.number }} opened by ${{ github.actor }} on ${{ github.ref }}"
          echo "Repo: ${{ github.repository }} | SHA: ${{ github.sha }}"
